trigger:
  - main
pool:
  vmImage: ubuntu-latest
variables:
  - group: test-dev

steps:


  - bash: |
      ls
      pwd
      cd $(Agent.BuildDirectory)
      ls
      pwd
    displayName: 'Build Zip Artifact test'


  - script: |
      aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
    displayName: 'Login to AWS - ECR'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_SESSION_TOKEN: $(AWS_SESSION_TOKEN)


  - task: Docker@2
    displayName: 'Building Docker Image with tags trial service'
    inputs:
      repository: 'demo-ecr-repo'
      command: 'build'
      Dockerfile: 'Dockerfile'
      tags: '$(Build.BuildNumber)'
      addPipelineData: false
      addBaseImageData: false


  - bash: |
      docker images
      docker tag demo-ecr-repo:$(Build.BuildNumber) 954678508118.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr-repo:$(Build.BuildNumber)
      docker push 954678508118.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr-repo:$(Build.BuildNumber)
    displayName: 'Docker Push with tags'


  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish Artifact: drop'
  #   inputs:
  #     PathtoPublish: '$(build.artifactstagingdirectory)/$(Build.BuildNumber).zip'