trigger:
  - main
pool:
  vmImage: ubuntu-latest
variables:
  - group: test-dev

steps:


  - bash: |
      ls
      pwd
      cd $(Agent.BuildDirectory)
      ls
      pwd
    displayName: 'Build Zip Artifact test'


  # - script: |
  #     aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
  #   displayName: 'Login to AWS - ECR'
  #   env:
  #     AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
  #     AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)


  # - task: Docker@2
  #   displayName: 'Building Docker Image with tags trial service'
  #   inputs:
  #     repository: 'test-service'
  #     command: 'build'
  #     Dockerfile: '$(Agent.BuildDirectory)/testadj/test/Dockerfile'
  #     tags: '$(Build.BuildNumber)'
  #     addPipelineData: false
  #     addBaseImageData: false


  # - bash: |
  #     docker images
  #     docker tag test-service:$(Build.BuildNumber) $(AWS_ACCOUNT_ID).dkr.ecr.us-east-1.amazonaws.com/test-service:$(Build.BuildNumber)
  #     docker push $(AWS_ACCOUNT_ID).dkr.ecr.us-east-1.amazonaws.com/test-service:$(Build.BuildNumber)
  #   displayName: 'Docker Push with tags'


  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish Artifact: drop'
  #   inputs:
  #     PathtoPublish: '$(build.artifactstagingdirectory)/$(Build.BuildNumber).zip'