# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    cat ./Dockerfile | docker run --rm -i hadolint/hadolint
    docker build -t demo-app-image .
    sudo ls /var/lib/docker/overlay2
    docker info
  displayName: Build docker image

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcessDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    