trigger:
  - main
pool:
  vmImage: ubuntu-latest
variables:
  - group: test-dev

steps:



  - script: |
      aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin 954678508118.dkr.ecr.$(AWS_REGION).amazonaws.com
    displayName: 'Login to AWS - ECR'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_SESSION_TOKEN: $(AWS_SESSION_TOKEN)
  

  - task: Docker@2
    displayName: 'Building Docker Image with tags trial service'
    inputs:
      repository: 'demo-ecr-repo'
      command: 'build'
      Dockerfile: 'Dockerfile'
      tags: 'latest'
      addPipelineData: false
      addBaseImageData: false
  
  
  - task: CmdLine@2
    displayName: "Run trivy scan"
    inputs:
      script: |
        trivy image --exit-code 0 --severity LOW,MEDIUM $(imageName):$(tag)
        trivy image --exit-code 1 --severity HIGH,CRITICAL $(imageName):$(tag)


  - bash: |
      docker images
      cat ./Dockerfile | docker run --rm -i hadolint/hadolint
      docker tag demo-ecr-repo:latest 954678508118.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr-repo:latest
      docker push 954678508118.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr-repo:latest
    displayName: 'Docker Push with tags'


  - task: CopyFiles@2
    displayName: 'Copy K8s Files to artifact directory'
    inputs:
       SourceFolder: 'K8s'
       Contents: |
          *
       TargetFolder: '$(build.artifactstagingdirectory)'
       CleanTargetFolder: true
       OverWrite: true
       flattenFolders: true

  - bash: |
      cd $(build.artifactstagingdirectory)
      zip -r k8s-$(Build.BuildNumber).zip *
    displayName: 'Build Zip'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      ArtifactName:  'k8sBuilds'
      PathtoPublish: '$(build.artifactstagingdirectory)/k8s-$(Build.BuildNumber).zip'