apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.name }}
  labels:
    app: {{ .Values.general.name  }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.general.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.general.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.general.containername }}
          image: "{{ .Values.image.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: 8080
    