apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3146
      protocol: TCP
      nodePort: 30080
  selector:
    app: {{ .Values.general.name }}
