apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app-container
        image: 954678508118.dkr.ecr.ap-south-1.amazonaws.com/demo-ecr-repo:demo-app
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 8080
      imagePullSecrets:
          - name: regcred
